### ISSUE TITLE
Show a confirmation once the build is done

### ISSUE THREAD

**Issue by Kryniol** [xsolve-pl/feater#27]
When the build has finished there is no information that the apps can be already accessed. It would be really helpful if the page would refresh itself or at least display some text text.

**Comment by malef** [comment]
Wondering if it would require some health check method (so not only when build is done and containers are started, but also after all after build tasks or building app in entrypoint succeeded.

**Comment by malef** [comment]
Done, also logs are being listed now allowing to debug problems.
