### ISSUE TITLE
Build definition inheritance 

### ISSUE THREAD

**Issue by aiprogMach** [xsolve-pl/feater#69]
Sometimes we need to use same definition with little alterations in many instances, currently we are just copy paste the definition. It will be useful to allow us doing this automatically, one suggestion is to allow making "abstract" definitions such as definition with key that have variable value instead of hard coded values, so when I need  that abstract definition I just need to set the real value of variable key.
example:
Abstract >
`{
"someKey": "@var",
"someKey2": "hardcodedValue"
}`
When I need that definition I can just extend this and set the value of `@var`.

**Comment by malef** [comment]
Not sure if we need templates functionality, but it would be good to be able to duplicate existing definitions and applying some modifications, as well as editing existing definitions.

**Comment by malef** [comment]
Added possibility to duplicate existing definitions.
